### ISSUE TITLE
Problem running litmus tests with herd

### ISSUE THREAD

**Issue by hernanponcedeleon** [paulmckrcu/litmus#10]
I'm trying to run some of the litmus tests from this repo using `herd7` (version `7.56`) with the cat models (and corresponding bell files) also in this repo, but I'm getting problems due to unbound vars, e.g.
```
herd7 auto/LB-GWR+R-Dd+R-Dd+R-Oc+OB-OB.litmus -model models/alan-kernel-2016.04.28.cat -bell models/alan-kernel-2016.04.28.bell
File "./models/alan-kernel-2016.04.28.bell", line 29, characters 27-32: unbound var: Start
```
The other models have the same problem (always `Start`). I took a quick look to the `herd7` source code (`main` branch), but could not find anything related to this kind of "events". 

Any idea what the problem might be? Am I missing any flag or do I need some special version of `herd7`?

**Comment by paulmckrcu** [comment]
On Mon, Jan 17, 2022 at 02:39:58AM -0800, Zeta wrote:
> I'm trying to run some of the litmus tests from this repo using `herd7` (version `7.56`) with the cat models (and corresponding bell files) also in this repo, but I'm getting problems due to unbound vars, e.g.
> ```
> herd7 auto/LB-GWR+R-Dd+R-Dd+R-Oc+OB-OB.litmus -model models/alan-kernel-2016.04.28.cat -bell models/alan-kernel-2016.04.28.bell
> File "./models/alan-kernel-2016.04.28.bell", line 29, characters 27-32: unbound var: Start
> ```
> The other models have the same problem (always `Start`). I took a quick look to the `herd7` source code (`main` branch), but could not find anything related to this kind of "events". 
> 
> Any idea what the problem might be? Am I missing any flag or do I need some special version of `herd7`?

I am using herd7 7.56+02~dev, Rev: c375ecc537da22070913496ad2043ae501c7ab78,
for what it is worth.

But there are several other things that need to be changed.

First, the official Linux-kernel memory model is now in the Linux kernel.
If you are comfortable using git (which presumably you are, given that
this message came via github):

git clone git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
cd linux/tools/memory-model
herd7 -conf linux-kernel.cfg path/to/litmus/test.litmus

Where "path/to/litmus/test.litmus" is replaced by the pathname to the
litmus test of interest.  Also, the "cd" command will of course need to
be adjusted if you choose a different directory name for your clone of
the Linux kernel.

Second, the current linux-kernel memory model only accepts C-language
litmus tests, not the LB-GWR+R-Dd+R-Dd+R-Oc+OB-OB.litmus file's
LISA format.  So, instead of auto/LB-GWR+R-Dd+R-Dd+R-Oc+OB-OB.litmus,
type auto/C-LB-GWR+R-Dd+R-Dd+R-Oc+OB-OB.litmus to get its C-language
counterpart.

Does that fix things for you?

							Thanx, Paul

**Comment by hernanponcedeleon** [comment]
Thanks for the reply @paulmckrcu.

I'm actually more interested in the LISA tests than the official LKMM. We are working in extending our CAT-based [BMC tool](https://github.com/hernanponcedeleon/Dat3M) to support the LISA format and I wanted to use all the LISA tests in this repo to compare the results of our tool with those obtained by herd.

Thus, I'm interested in running the LISA tests in this repo w.r.t **ANY** `.cat` model that supports the required instructions. The most interesting cases are those involving locks, but I'm not sure if those are still experimental as stated [here](https://github.com/herd/herdtools7/blob/ec247deebcaeb2505ef9e887c48910bb8dd109ec/catalogue/linux/cats/linux-kernel.cat#L17). Maybe @maranget can comment about this.

**Comment by paulmckrcu** [comment]
On Mon, Jan 17, 2022 at 08:28:19AM -0800, Zeta wrote:
> Thanks for the reply @paulmckrcu.
> 
> I'm actually more interested in the LISA tests than the official LKMM. We are working in extending our CAT-based [BMC tool](https://github.com/hernanponcedeleon/Dat3M) to support the LISA format and I wanted to use all the LISA tests in this repo to compare the results of our tool with those obtained by herd.
> 
> Thus, I'm interested in running the LISA tests in this repo w.r.t **ANY** `.cat` model that supports the required instructions. The most interesting cases are those involving locks, but I'm not sure if those are still experimental as stated [here](https://github.com/herd/herdtools7/blob/ec247deebcaeb2505ef9e887c48910bb8dd109ec/catalogue/linux/cats/linux-kernel.cat#L17). Maybe @maranget can comment about this.

Ah!

One approach would be to check out old versions of both the litmus repo
and the herdtools repo, with a goal of finding a Linux-kernel .cat file
in either the litmus repo or in the herdtools repo that matches both
herdtools and the LISA-language litmus tests.

My first guess would be mid-2017, if you are interested in locking.

One way to get a better starting date would be to look at when the
.litmus tests involving locks were created.

And yes, Luc most likely has much better information than I do!  ;-)

							Thanx, Paul

**Comment by maranget** [comment]
Hi @hernanponcedeleon , short answer: LISA has not been maintained, as a consequence herd does not work any more on LISA tests. 

More precisely the bell and cat files of the repository do not work. I side with @paulmckrcu when he suggests checking out old versions. herd itself probably is not very relevant. But checking out older versions of bell and cat files may be sufficient. Have you tried? MOreover I am not sure that this repository includes LISA tests using locks.
I mean checking out .bell and .cat files from the Linux repository https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/memory-model

**Comment by hernanponcedeleon** [comment]
I haven't check the different versions from the Linux repo, but I'll.

I think @maranget is right about no lock benchmarks in this repo. I saw there are a few in the Linux repo, but is there any more extensive test suite somewhere?

**Comment by paulmckrcu** [comment]
On Tue, Jan 18, 2022 at 03:30:46AM -0800, Luc Maranget wrote:
> Hi @hernanponcedeleon , short answer: LISA has not been maintained, as a consequence herd does not work any more on LISA tests. 

Thank you for the reminder!

> More precisely the bell and cat files of the repository do not work. I side with @paulmckrcu when he suggests checking out old versions. herd itself probably is not very relevant. But checking out older versions of bell and cat files may be sufficient. Have you tried? MOreover I am not sure that this repository includes LISA tests using locks.

There do not look to be any automatically generated LISA tests containing
locking.  And now that you mention it, I believe that we had switched
over to C-language litmus tests before we added locking.

While I am thinking of it, good show on the "Extending Intel-x86
Consistency and Persistency" paper.  This does give me more hope that
I/O devices might one day be formalized.  ;-)

							Thanx, Paul

**Comment by paulmckrcu** [comment]
On Tue, Jan 18, 2022 at 08:45:58AM -0800, Zeta wrote:
> I haven't check the different versions from the Linux repo, but I'll.
> 
> I think @maranget is right about no lock benchmarks in this repo. I saw there are a few in the Linux repo, but is there any more extensive test suite somewhere?

There are not quite 300 lock-related litmus tests in manual/locked in
the github litmus-test archive, if that helps.  There are several more
elsewhere as shown below.

							Thanx, Paul

------------------------------------------------------------------------

manual/absperf/C-SB+l-o-o-u+l-o-o-u+l-o-o-u+l-o-o-u+l-o-o-u.litmus
manual/absperf/C-SB+l-o-o-u+l-o-o-u+l-o-o-u+l-o-o-u.litmus
manual/absperf/C-SB+l-o-o-u+l-o-o-u+l-o-o-u.litmus
manual/absperf/C-SB+l-o-o-u+l-o-o-u.litmus
manual/atomic/C-lock-write1.litmus
manual/atomic/C-lock-write2.litmus
manual/atomic/C-lock2.litmus
manual/atomic/C-unlock-wait-00.litmus
manual/atomic/C-unlock-wait-01.litmus
manual/kernel/C-ISA2+l-o-o-ul+l-o-o-ul+o-mb-o.litmus
manual/kernel/C-ISA2+o-mb-o+l-o-o-ul+l-o-o-ul.litmus
manual/kernel/C-JanStancek-rwsem.litmus
manual/kernel/C-LB+l-o-o-ul+l-o-o-ul+o-mb-o.litmus
manual/kernel/C-LB+l-o-ul-l-o-ul+o-mb-o.litmus
manual/kernel/C-MP+l-o-ul-l-o-ul+o-mb-o.litmus
manual/kernel/C-MP+o-mb-o+l-o-ul-l-o-ul.litmus
manual/kernel/C-ManfredSpraul-L1G1lock.litmus
manual/kernel/C-ManfredSpraul-L1G1locknr.litmus
manual/kernel/C-ManfredSpraul-L1G2lock.litmus
manual/kernel/C-PaulEMcKenney-W+RWC4+2017-10-05.litmus
manual/kernel/C-PaulEMcKenney-psc+sr-mbacq.litmus
manual/kernel/C-PaulEMcKenney-psc+sr-mbonce.litmus
manual/kernel/C-PaulEMcKenney-psc+sr-po.litmus
manual/kernel/C-PaulEMcKenney-psc+sr-relacq.litmus
manual/kernel/C-PaulEMcKenney-psc+sr-relonce.litmus
manual/kernel/C-PaulEMcKenney-psc+sr-sr.litmus
manual/kernel/C-SB+l-o-ul-l-o-ul+o-mb-o.litmus
manual/kernel/C-W+WRC+l-o-o-ul+l-o-o-ul+o-mb-o.litmus
manual/kernel/C-seqlock.litmus
manual/kernel/C-viro-2020.09.29a.litmus
manual/kernel/C-viro-LB-locks-relacq.litmus
manual/kernel/LB-unlock-lock.litmus
manual/kernel/MP-unlock-lock.litmus
manual/kernel/SB-unlock-lock.litmus
manual/kernel/WRC-unlock-lock.litmus
manual/kernel/after-unlock-lock-same-cpu.litmus
manual/kernel/after-unlock-lock-same-lock-variable.litmus
manual/locked/2+2W+onces+locked.litmus
manual/locked/2+2W+po+rfi-po+onces+locked.litmus
manual/locked/2+2W+rfi-pos+onces+locked.litmus
manual/locked/3.2W+onces+locked.litmus
manual/locked/3.2W+po+rfi-po+po+onces+locked.litmus
manual/locked/3.2W+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/3.2W+rfi-pos+onces+locked.litmus
manual/locked/3.LB+onces+locked.litmus
manual/locked/3.SB+onces+locked.litmus
manual/locked/3.SB+po+rfi-po+po+onces+locked.litmus
manual/locked/3.SB+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/3.SB+rfi-pos+onces+locked.litmus
manual/locked/4.2W+onces+locked.litmus
manual/locked/4.2W+po+rfi-po+po+po+onces+locked.litmus
manual/locked/4.2W+po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/4.2W+po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/4.2W+po+rfi-po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/4.2W+rfi-pos+onces+locked.litmus
manual/locked/4.LB+onces+locked.litmus
manual/locked/4.SB+onces+locked.litmus
manual/locked/4.SB+po+rfi-po+po+po+onces+locked.litmus
manual/locked/4.SB+po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/4.SB+po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/4.SB+po+rfi-po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/4.SB+rfi-pos+onces+locked.litmus
manual/locked/IRIW+onces+locked.litmus
manual/locked/IRRWIW+onces+locked.litmus
manual/locked/IRWIW+onces+locked.litmus
manual/locked/ISA2+onces+locked.litmus
manual/locked/ISA2+rfi-po+po+po+onces+locked.litmus
manual/locked/LB+onces+locked.litmus
manual/locked/MP+onces+locked.litmus
manual/locked/MP+rfi-po+po+onces+locked.litmus
manual/locked/R+onces+locked.litmus
manual/locked/R+po+rfi-po+onces+locked.litmus
manual/locked/R+rfi-po+po+onces+locked.litmus
manual/locked/R+rfi-pos+onces+locked.litmus
manual/locked/RWC+onces+locked.litmus
manual/locked/RWC+po+rfi-po+onces+locked.litmus
manual/locked/S+onces+locked.litmus
manual/locked/S+rfi-po+po+onces+locked.litmus
manual/locked/SB+onces+locked.litmus
manual/locked/SB+po+rfi-po+onces+locked.litmus
manual/locked/SB+rfi-pos+onces+locked.litmus
manual/locked/W+RR+WR+WR+onces+locked.litmus
manual/locked/W+RR+WR+WR+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RR+WR+WR+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RR+WR+WR+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/W+RR+WR+WW+onces+locked.litmus
manual/locked/W+RR+WR+WW+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RR+WR+WW+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RR+WR+WW+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/W+RR+WW+RR+onces+locked.litmus
manual/locked/W+RR+WW+RR+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RR+WW+RW+onces+locked.litmus
manual/locked/W+RR+WW+RW+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RR+WW+WR+onces+locked.litmus
manual/locked/W+RR+WW+WR+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RR+WW+WR+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RR+WW+WR+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/W+RR+WW+WW+onces+locked.litmus
manual/locked/W+RR+WW+WW+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RR+WW+WW+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RR+WW+WW+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/W+RW+RR+WR+onces+locked.litmus
manual/locked/W+RW+RR+WR+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RW+RR+WW+onces+locked.litmus
manual/locked/W+RW+RR+WW+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RW+RW+RR+onces+locked.litmus
manual/locked/W+RW+RW+RW+onces+locked.litmus
manual/locked/W+RW+RW+WR+onces+locked.litmus
manual/locked/W+RW+RW+WR+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RW+RW+WW+onces+locked.litmus
manual/locked/W+RW+RW+WW+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RW+WR+WR+onces+locked.litmus
manual/locked/W+RW+WR+WR+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RW+WR+WR+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RW+WR+WR+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/W+RW+WR+WW+onces+locked.litmus
manual/locked/W+RW+WR+WW+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RW+WR+WW+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RW+WR+WW+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/W+RW+WW+RR+onces+locked.litmus
manual/locked/W+RW+WW+RR+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RW+WW+RW+onces+locked.litmus
manual/locked/W+RW+WW+RW+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RW+WW+WR+onces+locked.litmus
manual/locked/W+RW+WW+WR+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RW+WW+WR+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RW+WW+WR+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/W+RW+WW+WW+onces+locked.litmus
manual/locked/W+RW+WW+WW+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RW+WW+WW+po+rfi-po+po+onces+locked.litmus
manual/locked/W+RW+WW+WW+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/W+RWC+onces+locked.litmus
manual/locked/W+RWC+po+po+rfi-po+onces+locked.litmus
manual/locked/W+RWC+rfi-po+po+po+onces+locked.litmus
manual/locked/W+RWC+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WRC+onces+locked.litmus
manual/locked/WRR+2W+onces+locked.litmus
manual/locked/WRR+2W+po+rfi-po+onces+locked.litmus
manual/locked/WRW+2W+onces+locked.litmus
manual/locked/WRW+2W+po+rfi-po+onces+locked.litmus
manual/locked/WRW+WR+onces+locked.litmus
manual/locked/WRW+WR+po+rfi-po+onces+locked.litmus
manual/locked/WW+RR+WR+WR+onces+locked.litmus
manual/locked/WW+RR+WR+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RR+WR+WR+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RR+WR+WR+po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+RR+WR+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+RR+WR+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RR+WR+WR+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RR+WR+WR+rfi-po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+RR+WW+RR+onces+locked.litmus
manual/locked/WW+RR+WW+RR+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RR+WW+RR+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RR+WW+RW+onces+locked.litmus
manual/locked/WW+RR+WW+RW+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RR+WW+RW+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+RR+WW+RW+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RR+WW+WR+onces+locked.litmus
manual/locked/WW+RR+WW+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RR+WW+WR+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RR+WW+WR+po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+RR+WW+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+RR+WW+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RR+WW+WR+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RR+WW+WR+rfi-po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+RR+WR+onces+locked.litmus
manual/locked/WW+RW+RR+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+RR+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+RW+RR+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+RW+RR+onces+locked.litmus
manual/locked/WW+RW+RW+RR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+RW+RW+RW+onces+locked.litmus
manual/locked/WW+RW+RW+RW+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+RW+RW+WR+onces+locked.litmus
manual/locked/WW+RW+RW+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+RW+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+RW+RW+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+WR+WR+onces+locked.litmus
manual/locked/WW+RW+WR+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+WR+WR+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RW+WR+WR+po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+WR+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+RW+WR+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+WR+WR+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RW+WR+WR+rfi-po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+WW+RW+onces+locked.litmus
manual/locked/WW+RW+WW+RW+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RW+WW+RW+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RW+WW+WR+onces+locked.litmus
manual/locked/WW+RW+WW+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+WW+WR+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RW+WW+WR+po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+WW+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+RW+WW+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+RW+WW+WR+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+RW+WW+WR+rfi-po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+onces+locked.litmus
manual/locked/WW+WR+WR+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+po+rfi-po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+rfi-po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+rfi-po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+rfi-po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+rfi-po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WR+WR+WR+rfi-pos+onces+locked.litmus
manual/locked/WW+WR+WW+WR+onces+locked.litmus
manual/locked/WW+WR+WW+WR+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WR+WW+WR+po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WW+WR+po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WR+WW+WR+po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WW+WR+po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WR+WW+WR+po+rfi-po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WR+WW+WR+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WR+WW+WR+rfi-po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WR+WW+WR+rfi-pos+onces+locked.litmus
manual/locked/WW+WW+RR+WR+onces+locked.litmus
manual/locked/WW+WW+RR+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+RR+WR+po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+RR+WR+po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+RR+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+WW+RR+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+RR+WR+rfi-po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+RR+WR+rfi-po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+RW+RR+onces+locked.litmus
manual/locked/WW+WW+RW+RR+po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+RW+RR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+WW+RW+RR+rfi-po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+RW+RW+onces+locked.litmus
manual/locked/WW+WW+RW+RW+po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+RW+RW+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+WW+RW+RW+rfi-po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+RW+WR+onces+locked.litmus
manual/locked/WW+WW+RW+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+RW+WR+po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+RW+WR+po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+RW+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+WW+RW+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+RW+WR+rfi-po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+RW+WR+rfi-po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+onces+locked.litmus
manual/locked/WW+WW+WR+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+po+rfi-po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+rfi-po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+rfi-po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+rfi-po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+rfi-po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WR+WR+rfi-pos+onces+locked.litmus
manual/locked/WW+WW+WW+RR+onces+locked.litmus
manual/locked/WW+WW+WW+RR+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RR+po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RR+po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RR+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RR+rfi-po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RR+rfi-po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RW+onces+locked.litmus
manual/locked/WW+WW+WW+RW+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RW+po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RW+po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RW+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RW+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RW+rfi-po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+WW+RW+rfi-po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+onces+locked.litmus
manual/locked/WW+WW+WW+WR+po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+po+rfi-po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+rfi-po+po+po+po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+rfi-po+po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+rfi-po+po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+rfi-po+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+rfi-po+rfi-po+po+po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+rfi-po+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+rfi-po+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/WW+WW+WW+WR+rfi-pos+onces+locked.litmus
manual/locked/WWC+onces+locked.litmus
manual/locked/Z6.0+onces+locked.litmus
manual/locked/Z6.0+po+po+rfi-po+onces+locked.litmus
manual/locked/Z6.0+rfi-po+po+po+onces+locked.litmus
manual/locked/Z6.0+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/Z6.1+onces+locked.litmus
manual/locked/Z6.1+po+rfi-po+po+onces+locked.litmus
manual/locked/Z6.1+rfi-po+po+po+onces+locked.litmus
manual/locked/Z6.1+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/Z6.2+onces+locked.litmus
manual/locked/Z6.2+rfi-po+po+po+onces+locked.litmus
manual/locked/Z6.3+onces+locked.litmus
manual/locked/Z6.3+po+rfi-po+po+onces+locked.litmus
manual/locked/Z6.3+rfi-po+po+po+onces+locked.litmus
manual/locked/Z6.3+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/Z6.4+onces+locked.litmus
manual/locked/Z6.4+po+po+rfi-po+onces+locked.litmus
manual/locked/Z6.4+po+rfi-po+po+onces+locked.litmus
manual/locked/Z6.4+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/Z6.4+rfi-po+po+po+onces+locked.litmus
manual/locked/Z6.4+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/Z6.4+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/Z6.4+rfi-pos+onces+locked.litmus
manual/locked/Z6.5+onces+locked.litmus
manual/locked/Z6.5+po+po+rfi-po+onces+locked.litmus
manual/locked/Z6.5+po+rfi-po+po+onces+locked.litmus
manual/locked/Z6.5+po+rfi-po+rfi-po+onces+locked.litmus
manual/locked/Z6.5+rfi-po+po+po+onces+locked.litmus
manual/locked/Z6.5+rfi-po+po+rfi-po+onces+locked.litmus
manual/locked/Z6.5+rfi-po+rfi-po+po+onces+locked.litmus
manual/locked/Z6.5+rfi-pos+onces+locked.litmus
manual/locked/rel-acq-unlock-lock/unlock-lock-write-ordering-1.litmus
manual/locked/rel-acq-unlock-lock/unlock-lock-write-ordering-2.litmus
manual/locked/rel-acq-unlock-lock/unlock-lock-write-ordering-3.litmus
manual/plain/C-no-race.litmus

**Comment by hernanponcedeleon** [comment]
Ohhh since I was focusing on the LISA tests in this repo, I missed all those. Those should keep me entertained for a while. Thanks a lot for all the pointer.
